version: "3.5"
services:
  backend-container:
    container_name: pipa-backend
    image: pipa-backend-nodejs
    #restart: on-failure
    build:
      context: ./backend
      dockerfile: Dockerfile.dockerfile
      target: development
    env_file:
      ./backend/.env
    volumes:
      - ./backend:/backend-container/src
    ports:
      - 3000:3000

  frontend-container:
    container_name: pipa-frontend
    image: pipa-frontend-reactnative
    #restart: on-failure
    build:
      context: ./frontend
      dockerfile: Dockerfile.dockerfile
      target: development
    volumes:
      - ./frontend:/opt/frontend-container/app:delegated
      - ./frontend/package.json:/opt/frontend-container/package.json
      - ./frontend/package-lock.json:/opt/frontend-container/package-lock.json
  #    - notused:/opt/frontend-container/app/node_modules
    ports:
      - 19000:19000
      - 19001:19001
      - 19002:19002

